apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: jin00000/jenkins-k8s-lab:latest # <-- 确保这里的用户名和 Jenkinsfile 中一致
          ports:
            - containerPort: 8080

